[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps =
    mobizt/Firebase ESP32 Client     @ ^4.4.14
    adafruit/DHT sensor library      @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    marcoschwartz/LiquidCrystal_I2C  @ ^1.1.2
    bblanchon/ArduinoJson            @ ^7.0.0